Implemented a new python script for computing image averages more eff…
CoBrALab/optimized_antsMultivariateTemplateConstruction pull request #11
Opened 2021-07-21 17:38 UTC by Gab-D-G

…iciently and flexibly. The averaging for affine transforms is still under development.

2021-07-21 17:47 UTC, gdevenyi requested changes

2021-07-21 17:47 UTC, gdevenyi commented on modelbuild.sh
> +        echo ${SCRIPT_DIR}/get_average.py -o ${_arg_output_dir}/${reg_type}/${i}/average/template.nii.gz ${_arg_average_norm} --image_type image --method ${_arg_average_type} \
lets use long arugments in the script

2021-07-21 17:47 UTC, gdevenyi commented on modelbuild.sh
> +        echo ${SCRIPT_DIR}/get_average.py -o ${_arg_output_dir}/${reg_type}/${i}/average/template.nii.gz ${_arg_average_norm} --image_type image --method ${_arg_average_type} \
I think I'd like a better name here.

modelbuild_averager maybe?

2021-07-21 17:47 UTC, gdevenyi commented on get_average.py
> +        average = stats.trim_mean(concat_array, 0.15, axis=0)
Why not the default threshold.

Also please make configurable.

2021-07-21 17:47 UTC, gdevenyi commented on get_average.py
> +        if (opts.image_type=='warp' or opts.image_type=='image') and '.nii' in file:
this code could work on .nrrd or .mnc as well

2021-07-21 17:47 UTC, gdevenyi commented on get_average.py
> +        elif opts.image_type=='affine' and '.mat' in file:
I think this code probably works on .xfm as well

2021-07-21 17:47 UTC, gdevenyi commented on get_average.py
> +        average = np.median(concat_array,axis=0)
Can this be done with https://simpleitk.org/doxygen/latest/html/classitk_1_1simple_1_1MedianProjectionImageFilter.html ?

2021-07-21 17:47 UTC, gdevenyi commented on get_average.py
> +        average = np.mean(concat_array, axis=0)
CAn this be done with https://simpleitk.org/doxygen/latest/html/classitk_1_1simple_1_1MeanProjectionImageFilter.html

2021-07-21 17:54 UTC, Gab-D-G commented on get_average.py
> +        average = stats.trim_mean(concat_array, 0.15, axis=0)
There's no default with the function. I made a few try with around 10 images and 15% seemed reasonable. I will make it configurable.

2021-07-21 18:25 UTC, Gab-D-G commented on get_average.py
> +        average = stats.trim_mean(concat_array, 0.15, axis=0)
Should be now resolved.

2021-07-21 18:25 UTC, Gab-D-G commented on modelbuild.sh
> +        echo ${SCRIPT_DIR}/get_average.py -o ${_arg_output_dir}/${reg_type}/${i}/average/template.nii.gz ${_arg_average_norm} --image_type image --method ${_arg_average_type} \
Should be now resolved.

2021-07-21 18:25 UTC, Gab-D-G commented on get_average.py
> +        if (opts.image_type=='warp' or opts.image_type=='image') and '.nii' in file:
Should be now resolved.

2021-07-21 18:25 UTC, Gab-D-G commented on get_average.py
> +        elif opts.image_type=='affine' and '.mat' in file:
Should be now resolved.

2021-07-21 18:36 UTC, Gab-D-G commented on get_average.py
> +        average = np.median(concat_array,axis=0)
I don't get how to use these filters and apply it on multiple images. Do you have code examples?

2021-07-21 18:44 UTC, Gab-D-G commented on get_average.py
> +        average = np.median(concat_array,axis=0)
I believe that this is not to compute a median of multiple images, but instead apply a certain type of image filtering https://notebook.community/5x5x5x5/ReproTutorial/notebooks/01-SimpleITK-Filtering

2021-07-28 14:32 UTC, gdevenyi requested changes

2021-07-28 14:32 UTC, gdevenyi commented on modelbuild.sh
> +# ARG_OPTIONAL_SINGLE([average-type],[],[Type of averaging to apply during modelbuild],[trimmed_mean])
I don't want the default changed from the original script please.

2021-07-28 14:32 UTC, gdevenyi commented on modelbuild.sh
> +    echo AverageImages 3 ${_arg_output_dir}/startingtarget.nii.gz 2 "${_arg_inputs[@]}" > ${_arg_output_dir}/jobs/${_datetime}/initialaverage
What happened here? The options for the initial average are gone. Please restore them.

In addition. For anything `AverageImages` already does, I want to keep using `AverageImages` because I don't want to require python until someone absolutely wants to use it.

2021-07-28 14:32 UTC, gdevenyi commented on modelbuild.sh
> +          >> ${_arg_output_dir}/jobs/${_datetime}/${reg_type}_${i}_shapeupdate
As per above, I only want python used if it absolutely has to be. Use AverageImages for the versions it supports.

You can keep the python internal implementation there though, no point in removing it.

2021-07-28 14:32 UTC, gdevenyi commented on modelbuild.sh
> +            --file_list $(for j in "${!_arg_inputs[@]}"; do echo -n "${_arg_output_dir}/${reg_type}/${i}/transforms/$(basename ${_arg_inputs[${j}]} | sed -r 's/(.nii$|.nii.gz$)//g')_1Warp.nii.gz "; d
Again here, defaults must stay the same, and not require python.

2021-07-28 14:32 UTC, gdevenyi commented on modelbuild_averager.py
> +        quit()
`quit()` is not a correct way of exiting scripts, its only for the interactive terminal, you should use `sys.exit()`

2021-07-28 14:32 UTC, gdevenyi commented on modelbuild_averager.py
> +    output = os.path.abspath(opts.output)
why absolute paths? that's simply not needed

2021-07-28 14:32 UTC, gdevenyi commented on modelbuild_averager.py
> +            continue
this seems odd to me, there's no need for an else here as the input is either an affine or a image, it can never reach this conditional

2021-07-28 14:32 UTC, gdevenyi commented on modelbuild_averager.py
> +        average = stats.trim_mean(concat_array, opts.trim_percent/100, axis=0)
I would rather the input option be done as a 0-1 value.

2021-07-28 14:32 UTC, gdevenyi commented on modelbuild_averager.py
> +    parser.add_argument("--trim_percent", type=float, default=15,
I would rather the input here be a 0-1 fraction.

2021-07-28 14:32 UTC, gdevenyi commented on modelbuild_averager.py
> +        average = sm.robust.scale.huber(concat_array)
Have you tested this? The mean/median needed an axis specified, this doesn't have an axis value, do you need to some kind of looping and/or broadcast?

2021-07-28 14:32 UTC, gdevenyi commented on modelbuild_averager.py
> +    elif opts.image_type=='affine':
have you tested the affine?

2021-07-28 14:33 UTC, gdevenyi commented on README.md
> +      	--trim-percent: Percentage to cut off if using trimmed_mean (default: '15')
I'd like this to be a fraction 0-1

2022-07-11 20:38 UTC, Gab-D-G commented on get_average.py
> +        average = np.median(concat_array,axis=0)
I checked out the MedianProjectionImageFilter, and it seems it doesn't work on 4D images. If using only SITK images I need to first create a 4D image from the stack of images to average with sitk.JoinSeries applying https://simpleitk.org/doxygen/latest/html/classitk_1_1simple_1_1JoinSeriesImageFilter.html, and then take the median/mean on the 4th dimension with MedianProjectionImageFilter. However, it raises a data type error which usually indicate the 4D application is not implemented ```sitk::ERROR: Pixel type: 32-bit float is not supported in 4D by N3itk6simple27MedianProjectionImageFilterE.```

2022-07-11 20:39 UTC, Gab-D-G commented on get_average.py
> +        average = np.mean(concat_array, axis=0)
the same would apply here as with the MedianProjectionImageFilter

2022-07-11 22:54 UTC, gdevenyi commented on get_average.py
> +        average = np.median(concat_array,axis=0)
Report a reproducable bug on the github then, they're supposed to have added it (make sure you're using a dev snapshot first...)

2022-07-12 14:53 UTC, Gab-D-G commented on modelbuild_averager.py
> +        average = sm.robust.scale.huber(concat_array)
there are no axis specification, it does it over the first axis when I tested it https://www.statsmodels.org/dev/generated/statsmodels.robust.scale.Huber.html

2022-07-12 15:21 UTC, Gab-D-G commented on modelbuild_averager.py
> +    elif opts.image_type=='affine':
The outputs are similar, but not exactly the same. This was actually never used I realize. Not sure why I implemented this in the first place. I think I'll keep your original code there and remove the affine part.

2022-07-12 16:32 UTC, Gab-D-G commented on get_average.py
> +        average = np.median(concat_array,axis=0)
I was not at the right SimpleITK version, with a later version the MedianProjection works but not the MeanProjection. However, I don't obtain a sensible average when using the sitk projection as compared to the current numpy alternative, despite using the same set of images (numpy median on the left, sitk median on the right)

![image](https://user-images.githubusercontent.com/34081874/178545300-cd30d707-e3f6-41c1-9731-1054fb9b78df.png)

2022-07-12 16:52 UTC, gdevenyi commented on get_average.py
> +        average = np.median(concat_array,axis=0)
Okay, we stick for numpy for now, but this should be submitted as a bug with a reproducible comparison they can look at.

2022-07-12 19:01 UTC, closed without merging