Wrote new python script to compute averages from a set of images to r…
CoBrALab/optimized_antsMultivariateTemplateConstruction pull request #45
Opened 2022-07-12 19:58 UTC by Gab-D-G

…eplace the currently slow median implementation.

2022-07-13 14:44 UTC, gdevenyi requested changes

2022-07-13 14:44 UTC, gdevenyi commented on modelbuild_averager.py
> +                        """)
Trim fraction? I like you switched to fraction as requested, but the help is now misleading.

2022-07-13 14:44 UTC, gdevenyi commented on modelbuild_averager.py
> +                        or a set of affine or non-linear (warp) transforms.
> set of affine

this code doesn't do affines.

2022-07-25 15:28 UTC, Gab-D-G commented
is this alright?
```python
elif opts.method == 'efficient_trimmed_mean':
    # computes the average from the 20th,50th and 80th percentiles
    average = np.quantile(concat_array, (0.2,0.5,0.8),axis=0).mean(axis=0)
```

2022-07-25 15:51 UTC, gdevenyi commented
Yes, except its not a trimmed mean, its a "trimean". Please include the wikipedia link in the  comment.

2022-07-25 16:49 UTC, gdevenyi approved these changes

2022-07-25 16:49 UTC, merged