Welford optimization
CoBrALab/optimized_antsMultivariateTemplateConstruction pull request #90
Opened 2023-09-27 14:21 UTC by RyanHaniff

Changes made based on the feedback from the original PR https://github.com/CoBrALab/optimized_antsMultivariateTemplateConstruction/pull/88

2023-09-27 16:00 UTC, gdevenyi requested changes

2023-09-27 16:00 UTC, gdevenyi commented on sitk_image_math.py
> -    elif opts.method == 'var':
we've lost method=var here.

It should be handled still using welford's

2023-09-27 16:33 UTC, RyanHaniff commented on sitk_image_math.py
> -    elif opts.method == 'var':
Could we do `if opts.method == 'mean' or 'var':` since mean and variance will be done at the same time?

2023-09-27 16:48 UTC, gdevenyi commented on sitk_image_math.py
> -    elif opts.method == 'var':
need to handle how the filenames are done properly still in that case.

2023-09-27 18:34 UTC, RyanHaniff commented on sitk_image_math.py
> +        split_file_path = opts.output.split(".nii.gz")
Is there a check to see if the user put in the correct file extension?

2023-09-27 18:52 UTC, gdevenyi requested changes

2023-09-27 18:52 UTC, gdevenyi commented on sitk_image_math.py
> +            file_extension = [ext for ext in file_extensions if opts.output.endswith(ext)][0]
What if my extension is .nii.gz, will this match .nii first?

2023-09-27 18:52 UTC, gdevenyi commented on sitk_image_math.py
> +def welford_method(array, count, mean, squared_diff): # pseudocode for welford algo (https://jonisalonen.com/2013/deriving-welfords-method-for-computing-variance/)
Move comment about the origins to a proper python docstring for this funciton

2023-09-27 18:52 UTC, gdevenyi commented on sitk_image_math.py
> +            sitk.WriteImage(average_img, file_name)
This is only writing one file?

When I say method = var, I want var to be the primary file.
When I say method = mean, I want mean to be the primary file.

2023-09-27 18:52 UTC, gdevenyi commented on sitk_image_math.py
> +            split_file_path = opts.output.split(file_extension)
Take a look at rsplit so you don't accidentally split on these extensions being embeddded in a path or a longer filename.

2023-09-28 19:18 UTC, RyanHaniff commented on sitk_image_math.py
> +            file_extension = [ext for ext in file_extensions if opts.output.endswith(ext)][0]
Yes, I didnt think about that case. Will make a fix.

2023-09-28 19:57 UTC, RyanHaniff commented on sitk_image_math.py
> +            sitk.WriteImage(average_img, file_name)
The code you referenced only writes the var file, the whole [if block](https://github.com/RyanHaniff/optimized_antsMultivariateTemplateConstruction/blob/b0dc8e39129e8a42c3b7188eb5665e192bcc321b/sitk_image_math.py#L241-L255) will save a mean file and then the var file:
```python
    if image_type=='image':
        average_img = sitk.GetImageFromArray(average, isVector=False)
        average_img.CopyInformation(averageRef)
        sitk.WriteImage(average_img, opts.output)
        if opts.method == 'mean' or opts.method == 'var':
            average = variance.reshape(shape)
            average_img = sitk.GetImageFromArray(average, isVector=False)
            average_img.CopyInformation(averageRef)
            # check what type of file exntension the user provided
            file_extension = [ext for ext in file_extensions if opts.output.endswith(ext)][0]
            # split based on the extension type and add "_var" to the name
            split_file_path = opts.output.split(file_extension)
            file_name = split_file_path[0] + '_var' + file_extension
            print(file_extension)
            sitk.WriteImage(average_img, file_name)
```
If I understand what you are asking for, when method = var, then the primary saved file will be a var file. The secondary file to be saved will be the mean with '_mean' concatenated to the file name? And vice-versa if method = mean.

2023-10-02 16:42 UTC, gdevenyi commented on sitk_image_math.py
> +        split_file_path = opts.output.split(".nii.gz")
not currently, but ITK will bail out trying to write an extension it can't handle, it happens a bit late...

2023-10-02 16:42 UTC, gdevenyi commented on sitk_image_math.py
> +            sitk.WriteImage(average_img, file_name)
Correct

2023-10-03 20:09 UTC, RyanHaniff commented on sitk_image_math.py
> +def welford_algo(array, count, mean, squared_diff): # pseudocode for welford algo (https://jonisalonen.com/2013/deriving-welfords-method-for-computing-variance/)
Added some docs to this commit: https://github.com/RyanHaniff/optimized_antsMultivariateTemplateConstruction/commit/5fb4e53f8f32865e50d16ba32db6271fcdfd94a5

2023-10-03 20:13 UTC, RyanHaniff commented on sitk_image_math.py
> +            split_file_path = opts.output.split(file_extension)
Did a fix here https://github.com/RyanHaniff/optimized_antsMultivariateTemplateConstruction/commit/adb744135cb2ffd3e95afd88acf615b2535f5465

2023-10-06 17:38 UTC, RyanHaniff commented
After doing some updates based on @gdevenyi suggestions, unbiased standard deviation is now being calculated. 

Here are the results for runtime. Note that Welford method is calculating the mean and var/std at the same time. Compared to the previous way only mean or std or var was being calculated.

Runtime results: 
![runtime_welford-mean-var_vs_mean](https://github.com/CoBrALab/optimized_antsMultivariateTemplateConstruction/assets/20189245/d2163cfb-6dcd-4cca-8d75-4a5db7cf59de)

Mincstats results:
![welford-mean_vs_mean](https://github.com/CoBrALab/optimized_antsMultivariateTemplateConstruction/assets/20189245/79959dfd-eb40-481b-aabc-4aabe27d18b5)

2023-10-06 18:43 UTC, gdevenyi approved these changes

2023-10-06 18:43 UTC, gdevenyi commented
Great job!

2023-10-06 18:44 UTC, merged