timeseries and warp fix
CoBrALab/optimized_antsMultivariateTemplateConstruction pull request #93
Opened 2023-10-06 19:48 UTC by RyanHaniff

Fix that allows timeseries and warp images to use Welford's method.

2023-10-06 20:07 UTC, gdevenyi requested changes

2023-10-06 20:07 UTC, gdevenyi commented on sitk_image_math.py
> +                    array = array.flatten()/array.mean()
Not quite here,

We need this line:
`array = array.reshape(array.shape[0], -1) / array.reshape(array.shape[0], -1).mean(axis = 1, keepdims=True)`

2023-10-06 20:07 UTC, gdevenyi commented on sitk_image_math.py
> +                    array = array.flatten()
Here should be
`array = array.reshape(array.shape[0], -1)`

2023-10-07 00:17 UTC, RyanHaniff commented on sitk_image_math.py
> +                    array = array.flatten()/array.mean()
Good spot!

2023-12-22 00:19 UTC, merged